# Generated by Django 5.0.1 on 2024-02-08 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Mecanico',
        ),
    ]
