# Generated by Django 5.0.1 on 2024-02-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='costo_reparacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(choices=[('Cambio de aceite', 'Cambio de aceite'), ('Reemplazo de frenos', 'Reemplazo de frenos'), ('Alineación y balanceo', 'Alineación y balanceo'), ('Reparación de motor', 'Reparación de motor')], max_length=50),
        ),
    ]
